"""shared rate limit counters

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 04:20:41.322418

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_hits",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.CheckConstraint("hits > 0", name="ck_rate_limit_hits_positive"),
        sa.PrimaryKeyConstraint("key", "window_start", name="pk_rate_limit_hits"),
    )
    op.create_index(
        "ix_rate_limit_hits_window_start", "rate_limit_hits", ["window_start"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rate_limit_hits_window_start", table_name="rate_limit_hits")
    op.drop_table("rate_limit_hits")
    # ### end Alembic commands ###
