"""shop settings

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-05 06:52:48.398643

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sellers", sa.Column("stalled_days", sa.Integer(), server_default="30", nullable=False)
    )
    op.add_column(
        "sellers",
        sa.Column(
            "min_margin_pct", sa.Numeric(precision=5, scale=2), server_default="15", nullable=False
        ),
    )
    op.add_column(
        "sellers",
        sa.Column(
            "max_return_rate_pct",
            sa.Numeric(precision=5, scale=2),
            server_default="10",
            nullable=False,
        ),
    )
    op.add_column(
        "sellers", sa.Column("weekly_email", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("sellers", sa.Column("last_digest_sent_on", sa.Date(), nullable=True))
    op.create_check_constraint(
        "ck_sellers_stalled_days", "sellers", "stalled_days BETWEEN 1 AND 365"
    )
    op.create_check_constraint(
        "ck_sellers_min_margin", "sellers", "min_margin_pct BETWEEN -100 AND 100"
    )
    op.create_check_constraint(
        "ck_sellers_max_return_rate", "sellers", "max_return_rate_pct BETWEEN 0 AND 100"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for name in ("ck_sellers_stalled_days", "ck_sellers_min_margin", "ck_sellers_max_return_rate"):
        op.drop_constraint(name, "sellers", type_="check")
    op.drop_column("sellers", "last_digest_sent_on")
    op.drop_column("sellers", "weekly_email")
    op.drop_column("sellers", "max_return_rate_pct")
    op.drop_column("sellers", "min_margin_pct")
    op.drop_column("sellers", "stalled_days")
    # ### end Alembic commands ###
